### PR TITLE
Support ghc 9.2

### PR DESCRIPTION
**Pull request by robrix**
This PR adds support for ghc 9.2.

### CODE REVIEW

**Comment by robrix** [comment]
Once this goes green I'll push to hackage as well.

**Comment by robrix** [comment]
https://hackage.haskell.org/package/lingo-0.5.0.1/candidate is looking good. Gonna release.

**Comment by robrix** [comment]
Ended up releasing https://hackage.haskell.org/package/lingo-0.5.0.2/ after some confusion around versions.

**Comment by robrix** [comment]
And https://hackage.haskell.org/package/lingo-0.5.0.3 to resolve build failures.

**Review by patrickt — APPROVED** [review]

**Pull request merged**
